name: Deploy Website
on: 
  push:
    branches:
      - main
jobs:
  htmlBuild:
    name: Publish Website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Jinja
        run: pip install Jinja2
      - name: Build Project 
        run: python build_web.py 
      - name: Move Files
        run: |
          mv ./overview_html ../public/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: ../public
          branch: gh-pages
